#!/usr/bin/env bash
set -euo pipefail       # exit immediately in case of error

# Try to shrink the size of PDF files, using a Ghostscript command. See: https://www.digitalocean.com/community/tutorials/reduce-pdf-file-size-in-linux

# If the size of the PDF file has actually been reduced (at least 1 % shrinked), then the original file is renamed ‘.ORIGINAL.pdf’ and the new compressed file takes its name.
# If the PDF file could not be reduced in size, it means it is already optimized. shrink_pdf will report this and leave the document unchanged.

# For translations
. gettext.sh
export TEXTDOMAIN="$(basename "$0")"
TEXTDOMAINDIR="$(cd "$(dirname "$0")" && pwd)/locale"
if [ ! -d "${TEXTDOMAINDIR}" ]; then
    TEXTDOMAINDIR="/usr/share/locale"
fi
export TEXTDOMAINDIR


##### FUNCTIONS and basic initialization #####

# Command and version
this_script_name="$(basename "$0")"
this_script_version="1.2.0"

# Colors and highligh in outputs
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BOLD=$(tput bold)
RESET=$(tput sgr0)

ERR="${RED}${BOLD}"
OK="${GREEN}${BOLD}"
WARN="${YELLOW}${BOLD}"
HIGHLIGHT="${BOLD}"

# Display a given message then waits for any key to be pressed, then return
# $1: Optional message to display. Default: "Press any key...'"
function press_any_key () {
    echo
    if [ $# -ge 1 ]; then
        echo -n "${1}"
    else
        echo -n "$(eval_gettext "\${HIGHLIGHT}Press any key...\${RESET}")"
    fi
    read -s -n 1
    echo
}

# Exit this script with an exit code, possibly after a "press any key"
function exit_script () {
    local function_name=${FUNCNAME}
    local exit_message
    if [ $# -ge 2 ]; then
        exit_message="${2}"
    else
        exit_message="$(eval_gettext "\${HIGHLIGHT}Press any key to finish...\${RESET}")"
    fi
    if [ "${PRESS_ANY_KEY}" = true ]; then press_any_key "${exit_message}"; fi

    if [ $# -ge 1 ]; then
        exit ${1}
    else
        echo "$(eval_gettext "\${ERR}ERROR: \${function_name} function called with incorrect number of parameter.\${RESET}" )" 1>&2
        exit_script 255    # bug: function called with incorrect number of parameter
    fi
}

# --version
function show_version () {
    echo "${this_script_version}"
}

# --help
function show_help () {
    echo
    echo "$( eval_gettext "\${this_script_name} tries to shrink the size of PDF files." )"

    echo "$( eval_gettext "It works particularly well with PDF files containing unoptimized images, such as documents scanned with xsane." )"
    echo
    echo "$( eval_gettext "If successful, i.e., if the file has been reduced by at least 10%, the original file is renamed \"<name>.ORIGINAL[.ext]\" and the reduced file takes its name." )"
    echo "$( eval_gettext "When the reduction is less than 10%, \${this_script_name} reports this and leaves the document unchanged." )"
    echo
    echo "$( eval_gettext "Usage:    \${this_script_name} [OPTION]... PDF_FILE..." )"
    echo
    echo "$( eval_gettext "OPTION:" )"
    echo "$( eval_gettext "  -k  --press_any_key   Wait for any key to be pressed at the end." )"
    echo "$( eval_gettext "  -x  --extreme_shrink  Try to shrink even more, at the expense of quality." )"
    echo
    echo "$( eval_gettext "      --version         Output version information and exit." )"
    echo "$( eval_gettext "      --help            Display this help and exit." )"
    echo
    echo "$( eval_gettext "PDF_FILE:" )"
    echo "$( eval_gettext "    One or more PDF files to shrink." )"
    echo
    echo "$( eval_gettext "Exit status:" )"
    echo "$( eval_gettext "    0  Ok. (Some files may not be shrinked because already optimized.)" )"
    echo "$( eval_gettext "    1  Some files with errors trying to shrink or rename them." )"
    echo "$( eval_gettext "  253  Error: missing prerequisite." )"
    echo "$( eval_gettext "  254  Error in the arguments of the calling command line." )"
    echo "$( eval_gettext "  255  Program error (bug): wrong number of arguments for a function call, etc." )"
    echo
    echo "$( eval_gettext "Examples:" )"
    echo
    echo "$( eval_gettext "\${this_script_name} ./big_doc.pdf ./another_doc.pdf" )"
    echo "$( eval_gettext "  This will try to shrink the two pdf files." )" 
    echo
    echo "$( eval_gettext "\${this_script_name} -x ./big_doc.pdf" )"
    echo "$( eval_gettext "  With the -x option (or --extreme_shrink) this will try to shrink even more." )"
    echo
}

# Parse command line arguments. Also handles show_version and show_help
# globals set by this function:
#   FILES   → array of file arguments: they all exist (exit 2 if any does not exist)
#   PRESS_ANY_KEY, EXTREME_SHRINK → booleans
parse_args() {
    FILES=()
    PRESS_ANY_KEY=false
    EXTREME_SHRINK=false

    if [ $# -eq 0 ]; then
        show_help
        exit_script 0
    fi

    local parse_options=true arg

    while [ $# -gt 0 ]; do
        arg="$1"
        shift

        if [ "$parse_options" = true ]; then
            case "$arg" in
            --help)
                show_help
                exit_script 0
                ;;
            --version)
                show_version
                exit_script 0
                ;;
            -k|--press_any_key)
                PRESS_ANY_KEY=true
                continue
                ;;
            -x|--extreme_shrink)
                EXTREME_SHRINK=true
                continue
                ;;
# template to manage options with values
#             -o|--output)
#             if [ $# -lt 1 ]; then
#                 echo "$(eval_gettext "\${ERR}ERROR: Missing argument for \"\${arg}\".\${RESET}" )" 1>&2
#                 exit_script 254       # Error in the arguments of the calling command line
#             fi
#             OUTPUT="$1"
#             shift
#             continue
#             ;;
#            --)
#                parse_options=false
#                continue
#                ;;
            -*)
                echo "$(eval_gettext "\${ERR}ERROR: unknown option argument \"\${arg}\".\${RESET}" )" 1>&2
                exit_script 254       # Error in the arguments of the calling command line
                ;;
            esac
        fi

        if [ -f "$arg" ]; then
            FILES+=("$arg")
        else
            echo "$(eval_gettext "\${ERR}ERROR: cannot access \"\${arg}\". No such file.\${RESET}" )" 1>&2
            exit_script 254       # Error in the arguments of the calling command line
        fi

    done

    if [ ${#FILES[@]} -eq 0 ]; then
        echo "$(eval_gettext "\${ERR}ERROR: at least one FILE argument is required.\${RESET}" )" 1>&2
        exit_script 254       # Error in the arguments of the calling command line
    fi
}


# File base name, with the extension, if any
# $1 is the file path
# Result is returned via stdout
function file_name () {
    echo "${1##*/}"
}

# File Extension, if any. Example: '.pdf' 
# $1 is the file path
# Result is returned via stdout
# A '.' as first character of the file name is discarded for the search of the file extension. Ex: '.conf': no extension, '.conf.json':'.json' extension 
# When no extension, '' is returned
function file_extension () {
    local filename

    # Extract filename from path
    filename="$(file_name "${1}")"

    # If filename starts with a dot, remove it: it does not mean an extension
    if [[ "$filename" == .* ]]; then
        filename="${filename##.}"
    fi

    # If filename contains a dot, extract the extension
    if [[ "$filename" == *.* ]]; then
        echo ".${filename##*.}"
    else
        echo ""
    fi
}

# Removes the extension of a file path (the starting '.' is removed too)
# $1 is the file path
# Result is returned via stdout
function path_without_extension () {
    local file=${1}
    local ext="$(file_extension "${file}")"      # the file extension
    # remove the n last characters, n is file extension length
    if [ "${ext}" = "" ]; then 
        echo "${file}"
    else
        echo "${file::-$((${#ext}))}"
    fi
}

# Divide a number by 1000 with a required number of digits after the decimal point
# $1 is the number to divide by 1000
# $2 is the required number of digits after the decimal point
# Return the result to the Standard Output
function divide_by_1000 () {
    local function_name=${FUNCNAME}
    if [ $# -ne 2 ]; then
        echo "$(eval_gettext "\${ERR}ERROR: \${function_name} function called with incorrect number of parameter.\${RESET}" )" 1>&2
        exit_script 255    # bug: function called with incorrect number of parameter
    fi
    echo "scale=$2; $1/1000" | bc -l
}

# Compute the shrink percentage
# $1 is the original size
# $2 is the new size
# Return the result to the Standard Output
# Example: return "96.8" if $1 is 5808000 and $2 is 184000
function shrink_percent () {
    local function_name=${FUNCNAME}
    if [ $# != 2 ]; then
        echo "$(eval_gettext "\${ERR}ERROR: \${function_name} function called with incorrect number of parameter.\${RESET}" )" 1>&2
        exit_script 255    # bug: function called with incorrect number of parameter
    fi
    echo "scale=1; 100-$2*100/$1" | bc -l
}



##### MAIN ####


# Error exit if "gs" is not installed (Ghostscript command)
command -v gs  1>/dev/null 2>&1 || {
    echo "$(eval_gettext "\${ERR}ERROR: The \"gs\" command is required but not installed. (Ghostscript)\${RESET}" )" 1>&2
    exit_script 253       # Error: missing prerequisite
}

# Error exit if "bc" is not installed (Basic Calculator)
command -v bc  1>/dev/null 2>&1 || {
    echo "$(eval_gettext "\${ERR}ERROR: The \"bc\" command is required but not installed. (Basic Calulator)\${RESET}" )" 1>&2
    exit_script 253       # Error: missing prerequisite
}



# Parse command line arguments. Also handles show_version and show_help
# globals set by this function:
#   FILES   → array of file arguments: they all exist (exit 2 if any does not exist)
#   PRESS_ANY_KEY, EXTREME_SHRINK → booleans
parse_args "$@"

if [ "${EXTREME_SHRINK}" = "true" ]; then
    echo "$(gettext "Shrink mode: Extreme")"
fi


TEMP_SHRINKED_SUBEXT="$(gettext ".TEMP_SHRINKED")"      # The temporary name of the shrinked file will end with ".TEMP_SHRINKED.pdf"
ORIGINAL_SUBEXT="$(gettext ".ORIGINAL")"                # "bak" file name: the new name of the original PDF file will end with ".ORIGINAL.pdf"


# file counters
nb_file_ok=0                # Number of files successfully shrinked
nb_file_not_shrinked=0      # Number of files NOT shrinked: already small or previously processed.
nb_file_error=0             # Number of files with errors trying to shrink or rename them.


# Process every file provided as arguments
for input_file in "${FILES[@]}"
do
    echo

    file_extension="$(file_extension "${input_file}")"                  # file extension
    filepath_minus_ext="$(path_without_extension "${input_file}")"      # input file path without extension

    # normal case: the input file has NOT been already processed and renamed by this script
    result_file="${filepath_minus_ext}${TEMP_SHRINKED_SUBEXT}${file_extension}"     # The temporary name of the result file. It will be later renamed as the original source file name.
    bak_file=${filepath_minus_ext}${ORIGINAL_SUBEXT}${file_extension}               # The future name of the original PDF file (It will be renamed if the shrinking is successful)
    
    # file names for shorter output messages
    input_file_filename="$(file_name "${input_file}")"
    bak_file_filename="$(file_name "${bak_file}")"

    echo -n ">>> ${HIGHLIGHT}${input_file_filename}${RESET} <<< "

    # Skip the file if its corresponding original file (renamed as a "bak" file) exists in the same directory
    if [[ -f "${bak_file}" ]]; then
        echo "$( eval_gettext "\${WARN}SKIPPED\${RESET} because it is probably the shrinking result of \"\${bak_file_filename}\"" )"
        nb_file_not_shrinked=$((nb_file_not_shrinked+1))      # Number of files NOT shrinked: already small or previously processed.
        continue        # next file
    fi

    # Skip the file if it is a file already renamed .${ORIGINAL_SUBEXT}${file_extension}): it is an original file previously processed by this script.
    extension2="$(file_extension "${filepath_minus_ext}")"      # second extension
    if [ "${extension2}" = "${ORIGINAL_SUBEXT}" ]; then
        echo "$( eval_gettext "\${WARN}SKIPPED\${RESET} because it has been already shrinked before. To shrink it again, rename it: remove \"\${ORIGINAL_SUBEXT}\"." )"
        nb_file_not_shrinked=$((nb_file_not_shrinked+1))      # Number of files NOT shrinked: already small or previously processed.
        continue        # next file
    fi

    filesize_input_file=$(stat -c%s "${input_file}")                        # size of the original file
    filesize_input_file_kB="$(divide_by_1000 "${filesize_input_file}" 1)"   # size of the original file in kB
    
    # if the result file already exists (with its temporary name), then delete it. It could be the result of a previous shrinking attempt, interrupted before the renaming step.
    if [ -f "${result_file}" ]; then
        if ! rm "${result_file}" 1>/dev/null; then
            echo "$( eval_gettext "\${ERR}ERROR: unable to delete \"\${result_file}\" before starting shrinking. Check access rights.\${RESET}" )" 1>&2
            nb_file_error=$((nb_file_error+1))      # Number of files with errors trying to shrink or rename them.
            continue    # next file
        fi
    fi

    # Use a Ghostscript command to shrink the PDF file
    if [ "${EXTREME_SHRINK}" = "true" ]; then
        dpdfsettings_value=/screen
    else
        dpdfsettings_value=/ebook
    fi

    # run the gs command. if the exit code is not 0 then display an error, delete the temporary result file (if any), then continue with the next file
    if ! gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS="${dpdfsettings_value}" -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${result_file}" "${input_file}"  1>/dev/null 2>&1; then
        echo "$( eval_gettext "\${ERR}ERROR: The shrinking command failed and returned an error. Most likely this is not a valid PDF file.\${RESET}" )" 1>&2
        # if the result file exists, delete it because it is probably corrupted (it happens sometimes with 'gs')
        if [ -f "${result_file}" ]; then
            if ! rm "${result_file}" 1>/dev/null; then
                echo "$( eval_gettext "\${ERR}ERROR: something went wrong trying to delete the result file. Check access rights.\${RESET}" )" 1>&2
            fi
        fi
        nb_file_error=$((nb_file_error+1))      # Number of files with errors trying to shrink or rename them.
        continue    # next file
    fi
    
    # if the result temporay file does not exist, display an error, then continue with the next file
    if [ ! -f "${result_file}" ]; then
        echo "$( eval_gettext "\${ERR}ERROR: something went wrong, no shrinking result file.\${RESET}" )"
        nb_file_error=$((nb_file_error+1))      # Number of files with errors trying to shrink or rename them.
        continue    # next file
    fi

    # Verify that the result file shrink percentage is 10% or more: 
    # if so, rename the source file as a "bak" file (.ORIGINAL) and the result file will replace it, taking its name, 
    # else delete the result file: the source file was already optimized.
    filesize_result_file=$(stat -c%s "${result_file}")                              # size of the result file
    filesize_result_file_kB="$(divide_by_1000 "${filesize_result_file}" 1)"           # size of the result file in kB
    shrink_percent="$(shrink_percent "${filesize_input_file}" "${filesize_result_file}")"    # shrink percentage


    if (( $(echo "$shrink_percent < 10" | bc -l) )); then
    
        # The shrink percentage is less than 10%. Moreover it might be negative, meaning the result file is bigger
        echo "$( eval_gettext "\${WARN}NOT shrinked:\${RESET} most likely this file is already optimized." )"

        # Delete the result file
        if rm "${result_file}" 1>/dev/null; then
            nb_file_not_shrinked=$((nb_file_not_shrinked+1))      # Number of files NOT shrinked: already small or previously processed.
            continue    # next file
        else 
            echo "$( eval_gettext "\${ERR}ERROR: something went wrong trying to delete the result file. Check access rights.\${RESET}" )" 1>&2
            nb_file_error=$((nb_file_error+1))      # Number of files with errors trying to shrink or rename them.
            continue    # next file
        fi

    fi

    # Successful shrinking: renaming steps

    # rename the source file as a "bak" file (.ORIGINAL in English)
    
    if ! mv "${input_file}" "${bak_file}" 1>/dev/null; then
        echo "$( eval_gettext "\${ERR}ERROR: something went wrong after shrinking. Unable to rename the original file as \"\${bak_file}\". Check access rights.\${RESET}" )" 1>&2
        nb_file_error=$((nb_file_error+1))      # Number of files with errors trying to shrink or rename them.
        continue    # next file
    fi

    # rename the result file as the original file name    
    if ! mv "${result_file}" "${input_file}" 1>/dev/null; then
        echo "$( eval_gettext "\${ERR}ERROR: something went wrong after shrinking. Unable to rename the temporary result file name \"\${result_file}\" as the original file name. Check access rights.\${RESET}" )" 1>&2
        nb_file_error=$((nb_file_error+1))      # Number of files with errors trying to shrink or rename them.
        continue    # next file
    fi

    echo "$( eval_gettext "\${OK}\${shrink_percent} % shrinked.\${RESET}  (Original: \"\${bak_file_filename}\")" )"
    nb_file_ok=$((nb_file_ok+1))    # Number of files successfully shrinked
    
done
    
# End message
echo
echo $( eval_ngettext \
    "\${OK}\${nb_file_ok} file successfully shrinked.\${RESET}" \
    "\${OK}\${nb_file_ok} files successfully shrinked.\${RESET}" \
    "$nb_file_ok" )
if [ "${nb_file_not_shrinked}" -gt 0 ]; then 
    echo $( eval_ngettext \
        "\${OK}\${nb_file_not_shrinked} file NOT shrinked: already small or previously processed.\${RESET}" \
        "\${OK}\${nb_file_not_shrinked} files NOT shrinked: already small or previously processed.\${RESET}" \
        "$nb_file_not_shrinked" )
fi
if [ "${nb_file_error}" -gt 0 ]; then 
    echo $( eval_ngettext \
        "\${ERR}\${nb_file_error} file with error trying to shrink or rename it.\${RESET}" \
        "\${ERR}\${nb_file_error} files with errors trying to shrink or rename them.\${RESET}" \
        "$nb_file_error" )
    exit_script 1       # Some files with errors trying to shrink or rename them.
fi

exit_script 0       # Ok. (Some files may not be shrinked because already optimized.)
